import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";


const Nazanin = localFont({
  src: "./fonts/BNazanin.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Nazanin.className} antialiased bg-slate-800 min-h-screen flex`}>
        <main className="flex-1 flex justify-center items-center">{children}</main>
      </body>
    </html>
  );
}
